//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sony4Room
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostupnost
    {
        public int IdDostupnosti { get; set; }
        public string Naziv { get; set; }
        public Nullable<bool> Slobodna { get; set; }
        public Nullable<int> BrojPoslednjegRacuna { get; set; }
    }
}
