//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sony4Room
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnjigaSanka
    {
        public int IdKnjigaSanka { get; set; }
        public string NazivPica { get; set; }
        public Nullable<int> Stanje { get; set; }
        public Nullable<System.DateTime> PoslednjaIzmena { get; set; }
    }
}
