//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sony4Room
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.Stavkas = new HashSet<Stavka>();
        }
    
        public int IdRacuna { get; set; }
        public Nullable<System.DateTime> DatumR { get; set; }
        public Nullable<bool> Naplaceno { get; set; }
        public Nullable<bool> IzdatRacunPice { get; set; }
        public Nullable<bool> IzdatRacunIznajmljivanje { get; set; }
        public string CenaIznajmljvanja { get; set; }
        public string CenaPica { get; set; }
        public string UkupnaCena { get; set; }
        public Nullable<int> IdIznajmljivanje { get; set; }
    
        public virtual Iznajmljivanje Iznajmljivanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka> Stavkas { get; set; }
    }
}
