//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sony4Room
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slusalouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slusalouse()
        {
            this.Iznajmljivanjes = new HashSet<Iznajmljivanje>();
        }
    
        public int IdSlusalica { get; set; }
        public string CenaSlusalica { get; set; }
        public string NazivSlusalica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iznajmljivanje> Iznajmljivanjes { get; set; }
    }
}
