//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sony4Room
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SonyEntities : DbContext
    {
        public SonyEntities()
            : base("name=SonyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<Iznajmljivanje> Iznajmljivanjes { get; set; }
        public virtual DbSet<Joyped> Joypeds { get; set; }
        public virtual DbSet<Konzola> Konzolas { get; set; }
        public virtual DbSet<Pice> Pices { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Slusalouse> Slusalice { get; set; }
        public virtual DbSet<Stavka> Stavkas { get; set; }
        public virtual DbSet<Dostupnost> Dostupnosts { get; set; }
        public virtual DbSet<KnjigaSanka> KnjigaSankas { get; set; }
    }
}
